### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'itching' 

### ISSUE THREAD

**Issue by osaket** [itachi9604/healthcare-chatbot#2]

**Comment by osaket** [comment]
I tried running your chatbot, it does not work. I get the following:

for svm: 
1.0
Traceback (most recent call last):
  File "chat_bot.py", line 279, in <module>
    getSeverityDict()
  File "chat_bot.py", line 105, in getSeverityDict
    _diction={row[0]:int(row[0])}
ValueError: invalid literal for int() with base 10: 'itching'

Any fix around this?

**Comment by itachi9604** [comment]
If it is the matter that you probably are using VS code for execution of the code then please switch to Pycharm. If it doesn't help, just ping again. I will be happy to resolve your problem.

**Comment by Clara-z** [comment]
i also have the same problem (using pycharm)

**Comment by itachi9604** [comment]
Hello everyone, I really am sorry for that error. It was because of the try except statement for _diction.
I made correction to the code.  I ran it now. It is working fine.

**Comment by Hafsa469** [comment]
Hi! Can you please tell me the basic working of a tree that on which bases it is predicting the diseases because in mostly cases the irrelevant diseases are predicted?
Like for high_fever it is pedicting Arthritis while high fever is not in its symptoms.
